import { Banner } from "@/types/banner";

export const HERO_SLIDES: Banner[] = [
  {
    id: "hero-1",
    title: "Bring Warmth Into Every Corner",
    subtitle: "NEW COLLECTION",
    description: "Discover beautifully crafted home essentials designed to make every space feel elegant, comfortable, and inviting.",
    image: "/images/hero/hero-04.jpg",
    mediaUrl: "/images/hero/hero-04.jpg",
    mediaType: "image",
    ctaText: "Shop Collection",
    ctaLink: "/products",
    buttonText: "Shop Collection",
    buttonLink: "/products",
    displayOrder: 1,
    isActive: true,
  },
  {
    id: "hero-2",
    title: "Aesthetics of the Table",
    subtitle: "KITCHEN ESSENTIALS",
    description: "Elevate your culinary daily rituals with hand-thrown ceramic ware, clean brass accessories, and solid walnut boards.",
    image: "/images/hero/hero-03.jpg",
    mediaUrl: "/images/hero/hero-03.jpg",
    mediaType: "image",
    ctaText: "Shop Tableware",
    ctaLink: "/products?category=kitchen",
    buttonText: "Shop Tableware",
    buttonLink: "/products?category=kitchen",
    displayOrder: 2,
    isActive: true,
  },
  {
    id: "hero-3",
    title: "The Art of Slow Living",
    subtitle: "AMBIENT TEXTURES",
    description: "Wrap yourself in double-ply Mongolian wool throws and organic cotton blankets designed to breathe warmth into lounges.",
    image: "/images/hero/hero-02.jpg",
    mediaUrl: "/images/hero/hero-02.jpg",
    mediaType: "image",
    ctaText: "Explore Textiles",
    ctaLink: "/products?category=bedroom",
    buttonText: "Explore Textiles",
    buttonLink: "/products?category=bedroom",
    displayOrder: 3,
    isActive: true,
  },
];
