import { Product } from "@/types/product";

export const PRODUCTS: Product[] = [
  {
    id: "prod-1",
    sku: "LT-AUR-01",
    name: "Aurelia Brass Pendant Light",
    slug: "aurelia-brass-pendant-light",
    shortDescription: "Brushed spun brass dome light featuring a reflective internal glaze.",
    description: "Elegant spun brass dome light featuring a brushed metallic exterior and a reflective gold interior glaze. Designed to provide warm, down-focused ambient light for dining areas, kitchen islands, or modern offices.",
    price: 245,
    images: ["/images/products/product-01.jpg", "/images/products/product-20.jpg"],
    category: "Lighting",
    rating: 4.8,
    reviewsCount: 24,
    stock: 12,
    isFeatured: true,
    bestSeller: true,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-2",
    sku: "DC-TRA-02",
    name: "Sienna Travertine Catch-all Tray",
    slug: "sienna-travertine-tray",
    shortDescription: "Premium Honed Roman Travertine stone organizer tray.",
    description: "Premium Honed Roman Travertine stone block with smooth curved depressions for modern organization. Excellent tray for rings, keys, and desk clutter, crafted from natural solid stone.",
    price: 89,
    images: ["/images/products/product-02.jpg", "/images/products/product-06.jpg"],
    category: "Decoration",
    rating: 4.7,
    reviewsCount: 15,
    stock: 8,
    isFeatured: true,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-3",
    sku: "LS-CAS-03",
    name: "Cashmere Ribbed Lounge Throw",
    slug: "cashmere-ribbed-lounge-throw",
    shortDescription: "Ultra-fine rib-weave Mongolian cashmere throw blanket.",
    description: "Ultra-fine Mongolian ribbed cashmere weave providing luxurious lightweight insulation for beds or lounge sofas. Features elegant fringe borders and a cashmere weight that is incredibly soft.",
    price: 180,
    salePrice: 145,
    discountPercentage: 19,
    images: ["/images/products/product-03.jpg", "/images/products/product-05.jpg"],
    category: "Decoration",
    rating: 4.9,
    reviewsCount: 42,
    stock: 3,
    isFeatured: true,
    bestSeller: true,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-4",
    sku: "FR-SAN-04",
    name: "Noir Sandalwood Soy Wax Candle",
    slug: "noir-sandalwood-soy-candle",
    shortDescription: "Hand-poured candle in premium matte black ceramic jar.",
    description: "Hand-poured coconut soy candle infused with notes of sandalwood, warm amber, cardamom, and leather. Housed in a custom-engineered matte black ceramic jar.",
    price: 45,
    images: ["/images/products/product-04.jpg", "/images/products/product-02.jpg"],
    category: "Decoration",
    rating: 4.6,
    reviewsCount: 51,
    stock: 25,
    isFeatured: true,
    bestSeller: false,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-5",
    sku: "BD-BEL-05",
    name: "Belgian Linen Pillow Sham Set",
    slug: "belgian-linen-pillow-sham",
    shortDescription: "Double-woven breathable Belgian flax linen pillow shams.",
    description: "Set of two double-woven breathable Belgian flax linen pillow shams. Pre-washed for extreme softness and textured appearance.",
    price: 65,
    salePrice: 55,
    discountPercentage: 15,
    images: ["/images/products/product-05.jpg", "/images/products/product-13.jpg"],
    category: "Bedroom",
    rating: 4.5,
    reviewsCount: 18,
    stock: 15,
    isFeatured: false,
    bestSeller: false,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-6",
    sku: "KT-WAL-06",
    name: "Walnut Wood Hand-Carved Bowl",
    slug: "walnut-wood-carved-bowl",
    shortDescription: "Solid black walnut nesting food or fruit bowl.",
    description: "Nesting bowl hand-carved from solid black walnut logs. Coated in food-grade natural linseed oil to preserve organic grain lines.",
    price: 120,
    images: ["/images/products/product-06.jpg", "/images/products/product-08.jpg"],
    category: "Kitchen",
    rating: 4.8,
    reviewsCount: 8,
    stock: 0,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-7",
    sku: "DC-ALA-07",
    name: "Alabaster Organic Shaped Vase",
    slug: "alabaster-organic-shaped-vase",
    shortDescription: "Hand-sculpted white alabaster translucent vase.",
    description: "Hand-sculpted white alabaster vase displaying natural organic curves and subtle light translucency. Excellent for placing single botanical stems.",
    price: 160,
    images: ["/images/products/product-07.jpg", "/images/products/product-04.jpg"],
    category: "Decoration",
    rating: 4.7,
    reviewsCount: 29,
    stock: 4,
    isFeatured: true,
    bestSeller: true,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-8",
    sku: "KT-KYO-08",
    name: "Kyoto Ceramic Tea Set",
    slug: "kyoto-ceramic-tea-set",
    shortDescription: "Handmade ceramic teapot and cup collection.",
    description: "Authentic handmade ceramic teapot and four cups set directly from Kyoto kilns. Features a coarse sand glaze and natural rattan wrapped handles.",
    price: 210,
    salePrice: 185,
    discountPercentage: 12,
    images: ["/images/products/product-08.jpg", "/images/products/product-18.jpg"],
    category: "Kitchen",
    rating: 4.9,
    reviewsCount: 33,
    stock: 2,
    isFeatured: true,
    bestSeller: false,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-9",
    sku: "FN-CHA-09",
    name: "Warm Oak Woven Lounge Chair",
    slug: "warm-oak-woven-lounge-chair",
    shortDescription: "Solid white oak frame chair with hand-woven paper cord seat.",
    description: "Relaxed lounge chair crafted from solid white oak and features a natural paper cord seat hand-woven by local craftsmen. High-back support makes it perfect for reading corners.",
    price: 495,
    images: ["/images/products/product-09.jpg", "/images/products/product-15.jpg"],
    category: "Furniture",
    rating: 4.7,
    reviewsCount: 16,
    stock: 5,
    isFeatured: true,
    bestSeller: true,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-10",
    sku: "OF-DES-10",
    name: "Minimalist Brass Desk Organizer Set",
    slug: "minimalist-brass-desk-organizer",
    shortDescription: "Solid brass tray, pen cup, and letter holder.",
    description: "A three-piece desk organizer set made from heavy-gauge solid brass. Over time, the material develops a rich patina, adding unique workspace character.",
    price: 135,
    images: ["/images/products/product-10.jpg", "/images/products/product-01.jpg"],
    category: "Office",
    rating: 4.6,
    reviewsCount: 12,
    stock: 20,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-11",
    sku: "DC-WLK-11",
    name: "Classic Walnut Wall Clock",
    slug: "classic-walnut-wall-clock",
    shortDescription: "Quiet sweep wood wall clock with copper hands.",
    description: "Minimalist wall clock carved from solid American walnut wood, featuring spun copper hands and a quiet sweep Japanese movement (no ticking noise).",
    price: 110,
    images: ["/images/products/product-11.jpg", "/images/products/product-06.jpg"],
    category: "Decoration",
    rating: 4.4,
    reviewsCount: 9,
    stock: 14,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-12",
    sku: "DC-MIR-12",
    name: "Asymmetrical Brass Vanity Mirror",
    slug: "asymmetrical-brass-vanity-mirror",
    shortDescription: "Organic shaped mirror in thinned brass wire frame.",
    description: "Beautifully contoured vanity mirror framed in a thin brushed brass frame. Perfect for entryways, bedroom dressers, or guest bathroom accents.",
    price: 165,
    images: ["/images/products/product-12.jpg", "/images/products/product-07.jpg"],
    category: "Decoration",
    rating: 4.8,
    reviewsCount: 22,
    stock: 6,
    isFeatured: true,
    bestSeller: false,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-13",
    sku: "BD-COT-13",
    name: "Organic Waffle Knit Bed Blanket",
    slug: "organic-waffle-knit-blanket",
    shortDescription: "Pre-shrunk organic cotton waffle weave blanket.",
    description: "Incredibly cozy organic cotton blanket woven in a waffle structure. Light, highly breathable, yet warm enough for layering across all seasons.",
    price: 140,
    images: ["/images/products/product-13.jpg", "/images/products/product-03.jpg"],
    category: "Bedroom",
    rating: 4.9,
    reviewsCount: 30,
    stock: 9,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-14",
    sku: "ST-BOX-14",
    name: "Handwoven Seagrass Storage Boxes",
    slug: "handwoven-seagrass-storage-boxes",
    shortDescription: "Set of 3 nesting boxes with integrated lids.",
    description: "Nesting seagrass storage boxes woven by hand over iron frames. Great for hiding away workspace clutter, cables, or bathroom cosmetics.",
    price: 75,
    salePrice: 60,
    discountPercentage: 20,
    images: ["/images/products/product-14.jpg", "/images/products/product-10.jpg"],
    category: "Storage",
    rating: 4.5,
    reviewsCount: 14,
    stock: 18,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-15",
    sku: "DC-PLT-15",
    name: "Tapered Clay Planter Pot",
    slug: "tapered-clay-planter-pot",
    shortDescription: "Terra cotta clay pot with matching drainage dish.",
    description: "Tapered clay pot made of raw red terra cotta. Features clean, unglazed textures that allow plant root nodes to breathe naturally. Drainage dish included.",
    price: 40,
    images: ["/images/products/product-15.jpg", "/images/products/product-16.jpg"],
    category: "Decoration",
    rating: 4.6,
    reviewsCount: 20,
    stock: 22,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-16",
    sku: "DC-FRM-16",
    name: "Solid Oak Floating Picture Frame",
    slug: "solid-oak-floating-picture-frame",
    shortDescription: "Transparent double glass frame in light oak.",
    description: "Elegant floating picture frame made from FSC-certified white oak and double panes of plexiglass, creating a beautiful borderless suspension effect for prints.",
    price: 55,
    images: ["/images/products/product-16.jpg", "/images/products/product-11.jpg"],
    category: "Decoration",
    rating: 4.3,
    reviewsCount: 11,
    stock: 30,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-17",
    sku: "KT-CER-17",
    name: "Artisan Ceramic Salad Plate Set",
    slug: "artisan-ceramic-salad-plates",
    shortDescription: "Set of 4 hand-glazed stoneware side plates.",
    description: "Four hand-thrown stoneware plates glazed in a warm speckled oatmeal finish. Raised organic edges catch sauces, making them beautiful daily essentials.",
    price: 80,
    images: ["/images/products/product-17.jpg", "/images/products/product-08.jpg"],
    category: "Kitchen",
    rating: 4.7,
    reviewsCount: 19,
    stock: 11,
    isFeatured: false,
    bestSeller: true,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-18",
    sku: "KT-GLS-18",
    name: "Minimalist Glass Water Carafe",
    slug: "minimalist-glass-water-carafe",
    shortDescription: "Hand-blown borosilicate carafe with wood stopper.",
    description: "Hand-blown glass carafe capable of hot and cold temperatures. Includes a solid sphere walnut wood stopper that seals freshness.",
    price: 50,
    images: ["/images/products/product-18.jpg", "/images/products/product-17.jpg"],
    category: "Kitchen",
    rating: 4.6,
    reviewsCount: 25,
    stock: 14,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-19",
    sku: "LT-FLR-19",
    name: "Travertine Arch Floor Lamp",
    slug: "travertine-arch-floor-lamp",
    shortDescription: "Minimal brass arch lamp with a solid stone base.",
    description: "A commanding floor lamp featuring a brushed brass arched pole set into a 15lb solid beige travertine stone block. Provides soft overhead diffuse lighting.",
    price: 380,
    images: ["/images/products/product-19.jpg", "/images/products/product-09.jpg"],
    category: "Lighting",
    rating: 4.9,
    reviewsCount: 7,
    stock: 2,
    isFeatured: true,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-20",
    sku: "LT-TBL-20",
    name: "Minimalist Ceramic Table Lamp",
    slug: "minimalist-ceramic-table-lamp",
    shortDescription: "Terracotta base lamp with organic linen drum shade.",
    description: "Table lamp showing a textured terra cotta vessel base and a natural oatmeal linen shade. Perfect for warm bedside lighting.",
    price: 155,
    images: ["/images/products/product-20.jpg", "/images/products/product-01.jpg"],
    category: "Lighting",
    rating: 4.8,
    reviewsCount: 16,
    stock: 8,
    isFeatured: false,
    bestSeller: true,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-21",
    sku: "BD-SHM-21",
    name: "Stripe Organic Cotton Sheet Set",
    slug: "stripe-organic-cotton-sheets",
    shortDescription: "Sateen weave organic cotton bedsheet set.",
    description: "Organic long-staple cotton bedsheet set woven in a sateen weave for a silky, smooth drape. Detailed with fine charcoal pin-stripes.",
    price: 190,
    salePrice: 165,
    discountPercentage: 13,
    images: ["/images/products/product-21.jpg", "/images/products/product-13.jpg"],
    category: "Bedroom",
    rating: 4.7,
    reviewsCount: 31,
    stock: 5,
    isFeatured: true,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-22",
    sku: "FN-COF-22",
    name: "Honed Travertine Coffee Table",
    slug: "honed-travertine-coffee-table",
    shortDescription: "Aesthetic low-profile coffee table in Roman travertine.",
    description: "Low-profile coffee table built entirely from Roman travertine slabs. Honed surface highlights natural stone patterns while providing durability.",
    price: 750,
    images: ["/images/products/product-22.jpg", "/images/products/product-02.jpg"],
    category: "Furniture",
    rating: 4.9,
    reviewsCount: 5,
    stock: 1,
    isFeatured: true,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-23",
    sku: "FN-SHF-23",
    name: "White Oak Modular Bookcase",
    slug: "white-oak-modular-bookcase",
    shortDescription: "Open shelf modular storage bookcase unit.",
    description: "Open modular shelving unit crafted from solid white oak. Includes adjustable height brackets to align decorative ornaments and storage boxes.",
    price: 520,
    images: ["/images/products/product-23.jpg", "/images/products/product-22.jpg"],
    category: "Furniture",
    rating: 4.6,
    reviewsCount: 12,
    stock: 3,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-24",
    sku: "FN-DIN-24",
    name: "Solid Walnut Dining Table",
    slug: "solid-walnut-dining-table",
    shortDescription: "Six-seater dining table in rich American walnut.",
    description: "Six-seater rectangular table showing the deep chocolate hues of American walnut wood. Finished with an organic oil coating.",
    price: 980,
    images: ["/images/products/product-25.jpg", "/images/products/product-09.jpg"],
    category: "Furniture",
    rating: 4.8,
    reviewsCount: 10,
    stock: 2,
    isFeatured: true,
    bestSeller: true,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-25",
    sku: "DC-CAN-25",
    name: "Travertine Taper Candle Holder",
    slug: "travertine-taper-candle-holder",
    shortDescription: "Solid stone column candle holders - Set of 2.",
    description: "Two column candle holders made from solid travertine stone. Fits standard taper candles to complete dining table layouts.",
    price: 65,
    images: ["/images/products/product-24.jpg", "/images/products/product-04.jpg"],
    category: "Decoration",
    rating: 4.7,
    reviewsCount: 18,
    stock: 12,
    isFeatured: false,
    bestSeller: false,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  // Add additional products to reach 40 items
  {
    id: "prod-26",
    sku: "LT-SCN-26",
    name: "Glow Alabaster Wall Sconce",
    slug: "glow-alabaster-wall-sconce",
    shortDescription: "Solid white alabaster stone wall-mounted sconce light.",
    description: "Stunning wall sconce carved from solid white alabaster. When illuminated, the translucent stone glows warm and displays natural veins.",
    price: 185,
    images: ["/images/products/product-01.jpg", "/images/products/product-07.jpg"],
    category: "Lighting",
    rating: 4.8,
    reviewsCount: 14,
    stock: 7,
    isFeatured: false,
    bestSeller: false,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-27",
    sku: "DC-CUSH-27",
    name: "Boucle Accent Cushion Cover",
    slug: "boucle-accent-cushion-cover",
    shortDescription: "Textured cream boucle cushion cover with zipper.",
    description: "Textured cushion cover woven from heavy cream boucle yarn. Features an organic matte canvas backing and a robust YKK hidden zipper.",
    price: 45,
    images: ["/images/products/product-05.jpg", "/images/products/product-03.jpg"],
    category: "Decoration",
    rating: 4.6,
    reviewsCount: 22,
    stock: 30,
    isFeatured: false,
    bestSeller: true,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-28",
    sku: "KT-MUG-28",
    name: "Speckled Oatmeal Ceramic Mugs",
    slug: "speckled-oatmeal-ceramic-mugs",
    shortDescription: "Set of 2 hand-thrown stoneware coffee mugs.",
    description: "Two stoneware mugs featuring a comfortable thumb-rest handle and a beautiful speckled oatmeal glaze. Pre-washed for a textured matte touch.",
    price: 38,
    images: ["/images/products/product-18.jpg", "/images/products/product-08.jpg"],
    category: "Kitchen",
    rating: 4.9,
    reviewsCount: 38,
    stock: 20,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-29",
    sku: "BD-DUV-29",
    name: "Linen Duvet Bed Cover",
    slug: "linen-duvet-bed-cover",
    shortDescription: "Pure Belgian flax linen duvet cover with buttons.",
    description: "Pure Belgian flax linen duvet cover. Light, highly breathable, and pre-washed for vintage texture. Finished with real coconut shell buttons.",
    price: 220,
    images: ["/images/products/product-13.jpg", "/images/products/product-05.jpg"],
    category: "Bedroom",
    rating: 4.7,
    reviewsCount: 15,
    stock: 6,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-30",
    sku: "FN-TAB-30",
    name: "Travertine Side End Table",
    slug: "travertine-side-end-table",
    shortDescription: "Chunky column side table made of solid travertine.",
    description: "Chunky column table carved from honed roman travertine. Heavy-weight stone structure fits perfectly beside low-profile sofas.",
    price: 340,
    images: ["/images/products/product-22.jpg", "/images/products/product-19.jpg"],
    category: "Furniture",
    rating: 4.8,
    reviewsCount: 11,
    stock: 4,
    isFeatured: false,
    bestSeller: false,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-31",
    sku: "DC-VSE-31",
    name: "Raw Terracotta Sculptural Vase",
    slug: "raw-terracotta-sculptural-vase",
    shortDescription: "Organic shaped vase made of unglazed terracotta clay.",
    description: "Sculptural vessel crafted by hand from coarse unglazed terracotta clay. Showcases raw earthly textures and dual circular loop handles.",
    price: 75,
    images: ["/images/products/product-15.jpg", "/images/products/product-07.jpg"],
    category: "Decoration",
    rating: 4.5,
    reviewsCount: 20,
    stock: 14,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-32",
    sku: "KT-BRD-32",
    name: "Solid Oak Bread Cutting Board",
    slug: "solid-oak-bread-cutting-board",
    shortDescription: "Solid oak serving board with handle details.",
    description: "Heavy serving board cut from solid European oak wood. Detailed with parallel grooves to collect bread crumbs, and an integrated hanging hole.",
    price: 60,
    images: ["/images/products/product-06.jpg", "/images/products/product-17.jpg"],
    category: "Kitchen",
    rating: 4.7,
    reviewsCount: 16,
    stock: 10,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-33",
    sku: "LT-PEN-33",
    name: "Honed Stone Pendant Light",
    slug: "honed-stone-pendant-light",
    shortDescription: "Cylinder travertine stone shade hanging pendant.",
    description: "Minimalist hanging pendant lighting built from a block of honed travertine stone. Detailed with brass fittings and an adjustable braided cord.",
    price: 195,
    images: ["/images/products/product-20.jpg", "/images/products/product-02.jpg"],
    category: "Lighting",
    rating: 4.6,
    reviewsCount: 8,
    stock: 9,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-34",
    sku: "BD-MAT-34",
    name: "Linen Bed Mattress Protector",
    slug: "linen-bed-mattress-protector",
    shortDescription: "Quilted organic cotton mattress pad layer.",
    description: "Quilted mattress pad layer filled with 100% organic cotton fibers. Hypoallergenic, breathable, and designed for silent bed fitting.",
    price: 95,
    images: ["/images/products/product-21.jpg", "/images/products/product-13.jpg"],
    category: "Bedroom",
    rating: 4.4,
    reviewsCount: 14,
    stock: 12,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-35",
    sku: "FN-BEN-35",
    name: "Walnut Dining Bench Seat",
    slug: "walnut-dining-bench-seat",
    shortDescription: "Bench seat matching the walnut dining table.",
    description: "walnut wood bench seat designed to slide perfectly under the walnut dining table. Sturdy wood frame supports up to three adults.",
    price: 320,
    images: ["/images/products/product-25.jpg", "/images/products/product-06.jpg"],
    category: "Furniture",
    rating: 4.7,
    reviewsCount: 9,
    stock: 3,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-36",
    sku: "DC-CLAY-36",
    name: "Grey Ceramic Water Pitcher",
    slug: "grey-ceramic-water-pitcher",
    shortDescription: "Stoneware pitcher glazed in matte slate grey.",
    description: "Clay pitcher glazed in matte slate grey. Holds up to 1.5 liters of liquid, serving as both a table pitcher and a decorative flower vase.",
    price: 70,
    images: ["/images/products/product-17.jpg", "/images/products/product-15.jpg"],
    category: "Decoration",
    rating: 4.5,
    reviewsCount: 12,
    stock: 18,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-37",
    sku: "KT-GLS-37",
    name: "Fluted Beverage Tumblers",
    slug: "fluted-beverage-tumblers",
    shortDescription: "Set of 4 ribbed borosilicate drinking glasses.",
    description: "Four drinking glasses showing beautiful fluted vertical ribs. Made from borosilicate glass to withstand thermal shocks.",
    price: 45,
    images: ["/images/products/product-18.jpg", "/images/products/product-10.jpg"],
    category: "Kitchen",
    rating: 4.8,
    reviewsCount: 22,
    stock: 25,
    isFeatured: false,
    bestSeller: true,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-38",
    sku: "LT-CON-38",
    name: "Spun Brass Wall Lamp",
    slug: "spun-brass-wall-lamp",
    shortDescription: "Adjustable swing-arm brass reading wall lamp.",
    description: "Swing-arm wall reading lamp crafted from spun brass. Offers horizontal and vertical rotations to position lighting exactly where needed.",
    price: 145,
    images: ["/images/products/product-01.jpg", "/images/products/product-20.jpg"],
    category: "Lighting",
    rating: 4.6,
    reviewsCount: 17,
    stock: 6,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-39",
    sku: "BD-SHM-39",
    name: "Velvet Quilted Pillow Shams",
    slug: "velvet-quilted-pillow-shams",
    shortDescription: "Set of 2 quilted cotton velvet shams.",
    description: "Two quilted pillow shams made from fine cotton velvet. Gives a rich, luxurious texture and warmth to bed set assemblies.",
    price: 75,
    images: ["/images/products/product-05.jpg", "/images/products/product-21.jpg"],
    category: "Bedroom",
    rating: 4.7,
    reviewsCount: 13,
    stock: 14,
    isFeatured: false,
    bestSeller: false,
    newArrival: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prod-40",
    sku: "FN-STOOL-40",
    name: "Solid Oak Tripod Stool",
    slug: "solid-oak-tripod-stool",
    shortDescription: "Three-legged accent stool or plant stand.",
    description: "Minimalist three-legged stool carved from solid European white oak. Extremely versatile, serving as an accent seat or side table.",
    price: 110,
    images: ["/images/products/product-09.jpg", "/images/products/product-06.jpg"],
    category: "Furniture",
    rating: 4.8,
    reviewsCount: 15,
    stock: 8,
    isFeatured: false,
    bestSeller: false,
    newArrival: false,
    createdAt: new Date().toISOString(),
  },
];
